config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :create, :destroy] do
    resources :tasks, only: [:index, :create, :destroy] do
      member do
       patch :complete
      end
    end
  end
  get 'archives', to: 'lists#archives'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, length: { minimum: 1 }

  DOMAIN = %(Job Personal Else)
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :lists, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists.where(completed: false)
    @list = List.new
    @list.user = current_user
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to lists_path
    else
      flash[:notice] = "Your list couldn't be saved, please try again"
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def archives
    @lists = current_user.lists.where(completed: true)
  end

  private

  def list_params
    params.require(:list).permit(:title, :user_id, :domain)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list

  def index
    @tasks = @list.tasks
    @task = Task.new
  end

  def create
    @task = Task.new(params_task)
    @task.list = @list
    if @task.save
      redirect_to list_tasks_path(@list)
    else
      flash.now[:alert] = "Your task couldn't be saved, please try again"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_tasks_path(@list)
  end

  def complete
    @task = Task.find(params[:id])
    @task.state = 'done'
    if @task.save
      flash.now[:alert] = "Your task was completed"
      @list = @task.list
      pending = @list.tasks.reject { |task|  task.state == 'done'}
        if pending.empty?
          @list.update(completed: true, completed_at: Time.now)
          flash.now[:alert] = "Congratulations, you successfully completed all of the tasks' list !"
          UserMailer.with(user: current_user, list: @list).congrats.deliver_now
        end
      redirect_to list_tasks_path(@list)
    else
      flash.now[:alert] = "Your task cannot be completed"
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def params_task
    params.require(:task).permit(:content, :state, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoThisTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="full-screen"><%= yield %></div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for [@list] do |f|%>
<div class="form-new">
  <div class="list-add">
    <%= f.input_field :title%>
  </div>
  <div class="domain">
    <%= f.input_field :domain, placeholder: "-- DOMAIN --", collection: ["Job", "Personal", "Else"] %>
  </div>
  <div class="btn-form-add">
    <%= f.button :submit, '+', class: "btn-add"%>
  </div>
  <% end %>
</div>

app/views/lists/archives.html.erb
<div class="container">
  <div class="date text-center">
    <h2><strong>My archives</strong></h2>
  </div>

  <div class="lists">
    <div class="row"></p>
      <% @lists.each do |list| %>
        <%= link_to list_tasks_path(list), style: "text-decoration:none" do %>
           <div class="list-item col-12 col-md-6 col-lg-3">
            <% if list.domain == "Job" %>
              <div class="list-green text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% elsif list.domain == "Personal" %>
              <div class="list-orange text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% else %>
              <div class="list-grey text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="archives text-center">
    <p class="text-btn"><strong><%= link_to 'Back to my lists', lists_path, class: "btn-archives" %></strong></p>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">

  <div class="date text-center">
    <h1><strong><%= Time.now.strftime("%dth of %B, %Y") %></strong></h1>
  </div>

  <div class="lists">
    <div class="row">
      <% @lists.each do |list| %>
        <%= link_to list_tasks_path(list), style: "text-decoration:none" do %>
          <div class="list-item col-12 col-md-6 col-lg-3">
            <% if list.domain == "Job" %>
              <div class="list-green text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% elsif list.domain == "Personal" %>
              <div class="list-orange text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% else %>
              <div class="list-grey text-center rounded">
                <p class="list-title"><strong><%= list.title %></strong></p>
                <p class="list-delete"><%= link_to '<i class="fas fa-times"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: "Are you sure?" }, style: "color:grey" %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="add">
    <%= render 'form' %>
  </div>

  <div class="archives text-center">
    <p class="text-btn"><strong><%= link_to 'My archives', archives_path, class: "btn-archives" %></strong></p>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f|%>
<%= f.input :title %>
<%= f.button :submit %>
<% end %>

app/views/shared/_footer.html.erb
    <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This website was made with <i class="fas fa-heart"></i> by DoThisTask's team.
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/lists", class: "navbar-brand" do %>
    <%= image_tag 'logo', class: "logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Hi #{current_user.username} !", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Archives", archives_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My lists", lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<!-- 'aria-haspopup': true, 'aria-expanded': false  -->

app/views/tasks/_form.html.erb
<%= simple_form_for ([@list, @task]) do |f|%>
<div class="form-new">
  <div class="list-add">
    <%= f.input_field :content%>
  </div>
  <div class="btn-form-add">
    <%= f.button :submit, '+', class: "btn-add"%>
  </div>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="date text-center">
    <% if @list.domain == "Personal" %>
      <h1 class="task-title-yellow"><%= @list.title %></h1>
    <% elsif @list.domain == "Job" %>
      <h1 class="task-title-green"><%= @list.title %></h1>
    <% else %>
      <h1 class="task-title-grey"><%= @list.title %></h1>
    <% end %>
    <% unless @list.completed_at.nil? %>
    <h3><strong> Completed:   </strong><em><%= @list.completed_at.strftime("%dth of %B, %Y") %></em> </h3>
    <% end %>
  </div>

  <div class="tasks-list">
    <p><% @tasks.each do |task| %></p>
    <% if task.state == 'pending' %>
      <ul>
        <li class="task"><%= link_to '<i class="far fa-square"></i>'.html_safe, complete_list_task_path(@list, task), method: :patch, style: "color:grey" %>  <%= task.content %>  <%= link_to '<i class="fas fa-times"></i>'.html_safe, list_task_path(@list, task), method: :delete, style: "color:grey", class: "task-delete" %></li>
      </ul>
    <% else %>
      <ul>
        <li class="task done"><i class="far fa-check-square"></i> <%= task.content %> <%= link_to '<i class="fas fa-times"></i>'.html_safe, list_task_path(@list, task), method: :delete, style: "color:grey", class: "task-delete" %></li>
      </ul>
    <% end %>
    <% end %>
  </div>

  <%= render 'form' %>
  <div class="archives text-center">
        <p class="text-btn"><strong><%= link_to 'Back to my lists', lists_path, class: "btn-archives" %></strong></p>
  </div>
</div>